# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Firebase Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh " flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1098369115685:android:656fd3b3a378dc852501cc",
    firebase_cli_token: "1//03PFZVp6eWy4ICgYIARAAGAMSNwF-L9IrJLJVq4loFu34z1bsdirrlGdiXmxbqObJzWEjceSqtWVsis0-tCSBdkfr_mh-ZyPBBEY",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "moohamedmosstafa@gmail.com",
    release_notes: "First release by fastlane yooooou"

     
  )
  end

 
end
